### ISSUE TITLE
Update user emails 

### ISSUE THREAD

**Issue by dancastellani** [NYU-CI/dfadmin#61]
Email templates for Keycloak

* Welcome (new user)
* Reset Password
* Reset OTP

Add note of security at the end.
Point to new user instructions.

**Comment by rafael-ladislau** [comment]
Keycloak sends the following email: Forgot Password and User > username > Credentials > Reset Actions (Configure OTP and Update Password).

Please check if the e-mails have the correct workspace (workspace.adrf.cloud) and Keycloak (id.adrf.cloud) URL. (check also if it has the right URL for the environment (dev, stage, and prod).

DFAdmin has the update token and password e-mails. It should be deactivated or it should use Keycloak API to trigger Keycloak's e-mails.

Check DFAdmin welcome and password expiring e-mails. Check if the information on these e-mails is correct.
