### ISSUE TITLE
Password Autocomplete in Browser

### ISSUE THREAD

**Issue by rafael-ladislau** [NYU-CI/dfadmin#73]
The AUTOCOMPLETE   attribute is not disabled on an HTML FORM/INPUT element containing password   type input. Passwords may be stored in browsers and retrieved.

**Comment by joao-ferreira-rdx** [comment]
@rafael-ladislau is this related to ZAP Scanner issues? If so, I guess it can be discarded. The issue was not detected in the last scan.
